### ISSUE TITLE
Missing geodata on some buildings 

### ISSUE THREAD

**Issue by sahirmoosvi** [UBCGeodata/ubcv-buildings#1]
Using the geojson files for ubcv-buildings I tried to look for a set of buildings but could not find data on the following BLDG_ID: LIFE, PONC, BRKX, AAC, PCOH, PONF. I am using R and the sf package to read the geojson files. Would we be able to update the data to include these? The building codes I searched for came from scheduling data.

**Comment by ubcjjb** [comment]
Thanks for pointing this out. It looks like there are a few classrooms that do not map to buildings but to sub-buildings. We will add a CLASS_CODE field to both buildings and sub-buildings to deal with the exceptions.

**Comment by sahirmoosvi** [comment]
Great, thanks! On a related note, is there geodata on specific rooms I can grab? I am working at the building level to highlight the distribution of room sizes across campus because I could not find geodate on specific rooms.

**Comment by ubcjjb** [comment]
Room data from UBC Facilities space inventory can be joined to the data here on REC_ID, but room data itself is not georeferenced.  CLASS_CODE has been added to the appropriate datasets.
